name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Start server
        run: |
          java -jar path/to/your/server.jar &
          sleep 30  # Aguarde o servidor iniciar

      - name: Build and test
        run: mvn clean test  # Esse comando vai rodar os testes

  deploy:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: success()
    steps:
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Adicione aqui seu comando de deploy
